apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeusers
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubecontainer
          image: guada15/usercreator:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://admin-Isra:admin-Isra@cluster0.cpaxw.mongodb.net/commerce
            - name: PORT
              value: 8080
            - name: PERSISTENCE
              value: MONGO
            - name: MONGO_LINK
              value: mongodb+srv://admin-Isra:admin-Isra@cluster0.cpaxw.mongodb.net/commerce
            - name: GOOGLE_CLIENT_ID
              value: 686402135164-4vcug1n2svsvbvllt7efiad777vn7o8e.apps.googleusercontent.com
            - name: GOOGLE_CLIENT_SECRET
              value: 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
            - name: SECRET_JWT
              value: admin123
            - name: SECRET_SESSION
              value: admin123
            - name: GMAIL_USER_APP
              value: pivaguadalupe1504@gmail.com
            - name: GMAIL_PASS_APP
              value: axjjackxfxjcxsfw
          imagePullPolicy: Always