### 
GET http://localhost:8080/api/users/

###
GET http://localhost:8080/api/users/64f4ebfd610eb2aeb9a15749

### change role
PUT http://localhost:8080/api/users/premium/64eba5eb9fa0b87e89f04573/


###
DELETE http://localhost:8080/api/users/651619eeab392dddc655e7af
### Cleaner
DELETE http://localhost:8080/api/users