### 
GET http://localhost:8080/api/users/

###
GET http://localhost:8080/api/users/64f4ebfd610eb2aeb9a15749

###
PUt http://localhost:8080/api/users/64f4ebfd610eb2aeb9a15749 HTTP/1.1 
Content-Type: application/json

{
    "first_name": "Guadalupe"
}


### change role
PUT http://localhost:8080/api/users/premium/64eba5eb9fa0b87e89f04573/


###
DELETE http://localhost:8080/api/users/652603fc2ac82e81807646b5
### Cleaner
DELETE http://localhost:8080/api/users